String getLanguageCode(String language) {
    switch (language) {
      case "Arabic":
        return "ar";
      case "Bengali":
        return "bn";
      case "Czech":
        return "cs";
      case "Dutch":
        return "nl";
      case "English":
        return "en";
      case "French":
        return "fr";
      case "German":
        return "de";
      case "Gujarati":
        return "gu";
      case "Hindi":
        return "hi";
      case "Italian":
        return "it";
      case "Indonesian":
        return "id";
      case "Japanese":
        return "ja";
      case "Kannada":
        return "kn";
      case "Korean":
        return "ko";
      case "Lithuanian":
        return "lt";
      case "Malayalam":
        return "ml";
      case "Marathi":
        return "mr";
      case "Norwegian":
        return "no";
      case "Polish":
        return "pl";
      case "Romanian":
        return "ro";
      case "Russian":
        return "ru";
      case "Serbian":
        return "sr";
      case "Spanish":
        return "es";
      case "Swedish":
        return "sv";
      case "Tamil":
        return "ta";
      case "Telugu":
        return "te";
      case "Thai":
        return "th";
      case "Turkish":
        return "tr";
      case "Urdu":
        return "ur";
      case "Ukrainian":
        return "uk";
      case "Vietnamese":
        return "vi";
      case "Welsh":
        return "cy";
      default:
        return "--";
    }
  }
